# Puerto Backend
server.port=8080

# Elasticsearch
spring.elasticsearch.uris=http://localhost:9200

# CORS Global
spring.web.cors.allowed-origins=http://localhost:4200
spring.web.cors.allowed-methods=*
spring.web.cors.allowed-headers=*

# H2 / JPA Database (manteniendo tus configuraciones actuales)
spring.datasource.url=jdbc:h2:mem:calistenicdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.h2.console.enabled=true